# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EarlGreyDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  # pod 'LookinServer', :configurations => ['Debug']

  # Pods for EarlGreyDemo

  target 'EarlGreyDemoUITests' do
    # Pods for testing
    inherit! :search_paths
    pod 'EarlGrey'
  end

end
